config/routes.rb
Rails.application.routes.draw do
  resources :parkings do
    member do
      get :registration_numbers_by_color
      get :ticket_number_by_registration_number
      get :ticket_numbers_by_color
      post :park_car
      patch :remove_car
    end
  end  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/parking.rb
class Parking < ApplicationRecord
  belongs_to :parking_spot, class_name: 'ParkingSpot', foreign_key: 'spot_assigned'

  scope :valid, -> {where(is_active: true)}
  attribute :is_active, :boolean, default: true

  validates :car_registration_number, presence: true, format: { with: /\A[A-Z]{2}\d{2}[A-Z]{2}\d{4}\z/, message: "is not valid formate" }
  validates :car_color, presence: true

  def set_ticket_number
    self.update_column(:ticket_number, "TN/#{self.id.to_s.rjust(5, '0')}")
  end
end

app/models/parking_spot.rb
class ParkingSpot < ApplicationRecord
  has_many :parking

  scope :available, -> { where(occupied: false) }
  attribute :occupied, :boolean, default: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
  layout false
  def index
    @parkings = Parking.valid
  end

  def show
    @parking = Parking.new
    render(params[:id])
  end

  def registration_numbers_by_color
    @registration_numbers = Parking.valid.where(car_color: params[:car_color]).pluck(:car_registration_number)    
  end

  def ticket_number_by_registration_number
    @ticket_numbers= Parking.valid.where(car_registration_number: params[:car_registration_number]).pluck(:ticket_number)
  end

  def ticket_numbers_by_color
    @ticket_numbers = Parking.valid.where(car_color: params[:car_color]).pluck(:ticket_number)
  end

  def park_car
    available_slot = ParkingSpot.available.min_by(&:distance_from_entry)

    if available_slot.present?
      data = {spot_assigned: available_slot.id,
      car_registration_number: params[:parkings][:car_registration_number],
      car_color: params[:parkings][:car_color]}

      parking = Parking.new(data)

      if parking.save
        parking.set_ticket_number
        available_slot.update!(occupied: true)
        redirect_to action: 'index'
      else
        render json: { message: parking.errors.full_messages.join(', ') }
      end

    else
      render json: { message: "Parking spot are not available." }
    end
  end

  def remove_car
    parking = Parking.valid.find_by(spot_assigned:params[:parkings][:spot_number])
    if parking.present?
      parking.update!(is_active: false)
      parking.parking_spot.update!(occupied: false)
      redirect_to(:action => 'index')
    else
      render json: { message: "Parking spot is invalid" }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parkings_helper.rb
module ParkingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Parking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/parkings/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
      background-color: #f4f4f4;
    }

    h1 {
      text-align: center;
      margin-top: 20px;
    }

    .button {
      display: inline-block;
      padding: 10px 20px;
      background-color: #007bff;
      color: white;
      text-decoration: none;
      border-radius: 5px;
      margin: 5px;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 20px;
      background-color: white;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    th, td {
      padding: 10px;
      text-align: left;
    }

    th {
      background-color: #f2f2f2;
    }

    tr:nth-child(even) {
      background-color: #f2f2f2;
    }
  </style>
</head>
<body>
  <h1>Parkings</h1>
  <%= link_to('Park New Car', 'parkings/park_car', class: 'button') %><br>
  <%= link_to('Remove car from parking', 'parkings/remove_car', class: 'button') %><br>
  <%= link_to('Registration Numbers by Color', 'parkings/registration_numbers_by_color', class: 'button') %><br>
  <%= link_to('Ticket Numbers by Registration number', 'parkings/ticket_number_by_registration_number', class: 'button') %><br>
  <%= link_to('Ticket Numbers by by Color', 'parkings/ticket_numbers_by_color', class: 'button') %><br>

  <table>
    <thead>
      <tr>
        <th>Serial ID</th>
        <th>Car Registration Number</th>
        <th>Car Color</th>
        <th>Spot Assigned</th>
        <th>Ticket Number</th>
        <th>Entry At</th>
      </tr>
    </thead>
    <tbody>
      <% @parkings.each do |parking| %>
        <tr>
          <td><%= parking.id %></td>
          <td><%= parking.car_registration_number %></td>
          <td><%= parking.car_color %></td>
          <td><%= parking.spot_assigned %></td>
          <td><%= parking.ticket_number%></td>
          <td><%= parking.created_at.utc.strftime('%Y-%m-%d %H:%M:%S')%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</body>
</html>

app/views/parkings/park_car.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Park Car</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f2f2f2;
      margin: 0;
      padding: 0;
    }
    h1 {
      background-color: #333;
      color: #fff;
      padding: 20px;
      margin: 0;
    }
    form {
      background-color: #fff;
      padding: 20px;
      margin: 20px;
      border-radius: 5px;
      box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.3);
    }
    label {
      font-weight: bold;
      display: block;
      margin-bottom: 5px;
    }
    input[type="text"], input[type="submit"] {
      padding: 5px;
      margin: 5px 0;
      border: 1px solid #ccc;
      border-radius: 3px;
      width: 100%;
    }
  </style>
</head>
<body>
  <h1>Park Car</h1>
  <%= form_for :parkings, url: park_car_parking_path, method: :post do |f| %>
    <%= f.label :car_registration_number, "Car Registration Number:" %>
    <%= f.text_field :car_registration_number %><br>

    <%= f.label :car_color, "Car Color:" %>
    <%= f.text_field :car_color %><br>

    <%= f.submit "Park Car" %>
  <% end %>
</body>
</html>

app/views/parkings/registration_numbers_by_color.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Registration Numbers by Color</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f2f2f2;
      margin: 0;
      padding: 0;
    }
    h1 {
      background-color: #333;
      color: #fff;
      padding: 20px;
      margin: 0;
    }
    form {
      background-color: #fff;
      padding: 10px;
      margin: 20px;
      border-radius: 5px;
      box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.3);
    }
    label {
      font-weight: bold;
    }
    select, input[type="submit"] {
      padding: 5px;
      margin: 2px 0;
      border: 1px solid #ccc;
      border-radius: 3px;
      width: 100%;
    }
    ul {
      list-style-type: none;
      padding: 0;
    }
    li {
      background-color: #fff;
      padding: 10px;
      margin: 5px;
      border-radius: 5px;
      box-shadow: 0px 0px 3px rgba(0, 0, 0, 0.1);
    }
    p {
      margin: 20px;
    }
    .back-link {
    display: inline-block;
    padding: 10px 20px;
    margin: 20px;
    background-color: #333;
    color: #fff;
    text-decoration: none;
    border-radius: 5px;
    box-shadow: 0px 0px 3px rgba(0, 0, 0, 0.3);
  }

  .back-link:hover {
    background-color: #555;
  }
  </style>
</head>
<body>
  <h1>Registration Numbers by Color</h1>

  <%= form_tag registration_numbers_by_color_parking_path, method: :get do %>
    <label for="color">Select Color:</label><br>
    <%= select_tag :car_color, options_for_select(Parking.valid.pluck(:car_color).uniq) %><br>
    <%= submit_tag "Search" %>
  <% end %>

  <% if params[:car_color].present? %>
    <% if @registration_numbers.present? %>
      <h2>Registration Numbers of Cars with Color: <%= params[:car_color] %></h2>
      <ul>
        <% @registration_numbers.each do |registration_number| %>
          <li><%= registration_number %></li>
        <% end %>
      </ul>
      <%= link_to "Back to Parkings", parkings_path, class: "back-link"%>
    <% else %>
      <p>No cars found for the selected color.</p>
      <%= link_to "Back to Parkings", parkings_path, class: "back-link"%>
    <% end %>
  <% end %>
</body>
</html>

app/views/parkings/remove_car.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Remove Car</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f2f2f2;
      margin: 0;
      padding: 0;
    }
    h1 {
      background-color: #333;
      color: #fff;
      padding: 20px;
      margin: 0;
    }
    form {
      background-color: #fff;
      padding: 20px;
      margin: 20px;
      border-radius: 5px;
      box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.3);
    }
    label {
      font-weight: bold;
    }
    input[type="number"], input[type="submit"] {
      padding: 5px;
      margin: 5px 0;
      border: 1px solid #ccc;
      border-radius: 3px;
      width: 100%;
    }
  </style>
</head>
<body>
  <h1>Remove Car</h1>
  <%= form_for :parkings, url: remove_car_parking_path, method: :patch do |f| %>
    <label for="spot_number">Enter Spot Number:</label>
    <%= f.number_field :spot_number %>
    <%= f.submit "Remove Car" %>
  <% end %>
</body>
</html>

app/views/parkings/ticket_number_by_registration_number.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ticket Number by Registration Number</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f2f2f2;
      margin: 0;
      padding: 0;
    }
    h1 {
      background-color: #333;
      color: #fff;
      padding: 20px;
      margin: 0;
    }
    form {
      background-color: #fff;
      padding: 10px;
      margin: 20px;
      border-radius: 5px;
      box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.3);
    }
    label {
      font-weight: bold;
    }
    input[type="text"], input[type="submit"] {
      padding: 5px;
      margin: 2px 0;
      border: 1px solid #ccc;
      border-radius: 3px;
      width: 100%;
    }
    p {
      margin: 20px;
    }
    .back-link {
    display: inline-block;
    padding: 10px 20px;
    margin: 20px;
    background-color: #333;
    color: #fff;
    text-decoration: none;
    border-radius: 5px;
    box-shadow: 0px 0px 3px rgba(0, 0, 0, 0.3);
  }

  .back-link:hover {
    background-color: #555;
  }
  </style>
</head>
<body>
  <h1>Ticket Number by Registration Number</h1>

  <%= form_tag ticket_number_by_registration_number_parking_path, method: :get do %>
    <label for="car_registration_number">Enter Vehicle Number:</label><br>
    <%= text_field_tag :car_registration_number %><br>
    <%= submit_tag "Search" %>
  <% end %>

  <% if @ticket_numbers.present? %>
    <ul>
      <% @ticket_numbers.each do |ticket_number| %>
        <li>Ticket Number: <%= ticket_number %></li>
      <% end %>
    </ul>
    <%= link_to "Back to Parkings", parkings_path, class: "back-link"%>
  <% elsif params[:car_registration_number].present? %>
    <p>No ticket found for the entered registration number.</p>
    <%= link_to "Back to Parkings", parkings_path, class: "back-link"%>
  <% end %>
</body>
</html>

app/views/parkings/ticket_numbers_by_color.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ticket Numbers by Car Color</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f2f2f2;
      margin: 0;
      padding: 0;
    }
    h1 {
      background-color: #333;
      color: #fff;
      padding: 20px;
      margin: 0;
    }
    form {
      background-color: #fff;
      padding: 20px;
      margin: 20px;
      border-radius: 5px;
      box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.3);
    }
    label {
      font-weight: bold;
    }
    select, input[type="submit"] {
      padding: 5px;
      margin: 5px 0;
      border: 1px solid #ccc;
      border-radius: 3px;
      width: 100%;
    }
    ul {
      list-style-type: none;
      padding: 0;
    }
    li {
      background-color: #fff;
      padding: 10px;
      margin: 5px;
      border-radius: 5px;
      box-shadow: 0px 0px 3px rgba(0, 0, 0, 0.1);
    }
    p {
      margin: 20px;
    }
    .back-link {
    display: inline-block;
    padding: 10px 20px;
    margin: 20px;
    background-color: #333;
    color: #fff;
    text-decoration: none;
    border-radius: 5px;
    box-shadow: 0px 0px 3px rgba(0, 0, 0, 0.3);
  }

  .back-link:hover {
    background-color: #555;
  }
  </style>
</head>
<body>
  <h1>Ticket Numbers by Car Color</h1>

  <%= form_tag ticket_numbers_by_color_parking_path, method: :get do %>
    <label for="car_color">Select Color:</label>
    <%= select_tag :car_color, options_for_select(Parking.valid.pluck(:car_color).uniq) %>
    <%= submit_tag "Search" %>
  <% end %>

  <% if params[:car_color].present? %>
    <% if @ticket_numbers.present? %>
      <h2>Ticket Numbers of Cars with Color: <%= params[:car_color] %></h2>
      <ul>
        <% @ticket_numbers.each do |ticket_number| %>
          <li><%= ticket_number %></li>
        <% end %>
      </ul>
      <%= link_to "Back to Parkings", parkings_path, class: "back-link"%>
    <% else %>
      <p>No cars found for the selected color.</p>
      <%= link_to "Back to Parkings", parkings_path, class: "back-link"%>
    <% end %>
  <% end %>
</body>
</html>